### ISSUE TITLE
Add a hint message when mouse hover the macro call

### ISSUE THREAD

**Issue by zearoby** [mikmart/vscode-sas#1]
Hi @mikmart ,

Thanks for your wonderful VSCode extension, and it helps me a lot to go to the macro definition file. But sometime, I just want to have a quick look in the macro definition parameters when I hover the mouse over the macro. Is it possible to be a new function in this extension?

Thanks a lot

**Comment by mikmart** [comment]
Thanks @Mr-ZBin! I'm glad to hear the extension has proven useful to others, too. And thanks for the suggestion; it would certainly be a useful feature. I'll have a look and see if I could find a way to make that work.

**Comment by zearoby** [comment]
@mikmart  Thank you so much. I'm looking forward for your good news.

**Comment by zearoby** [comment]
Hi @mikmart , I have created a hint message extension by using "vscode.languages.registerHoverProvider" API.
[hover.zip](https://github.com/mikmart/vscode-sas/files/10008710/hover.zip)
![image](https://user-images.githubusercontent.com/22544491/201815975-5de30adb-3a5f-4569-b472-cbe81f9255a8.png)

Thanks.

**Comment by mikmart** [comment]
@Mr-ZBin I added an initial version of the hover provider. It'll show the signature of the hovered user-defined macro. I haven't released it on the extension marketplace yet, but it's here on Github. Feel free to try it out.

**Comment by zearoby** [comment]
Hi @mikmart, thanks for your update. I'll close the ticket.

**Comment by mikmart** [comment]
v0.1.0 including this feature is now also published on the marketplace.
