### ISSUE TITLE
Unclear how to set macro path

### ISSUE THREAD

**Issue by rudvfaden** [mikmart/vscode-sas#2]
The follow info is from the install path

_This extension contributes the following settings:

sas.sasautos: Paths to SAS autocall macro libraries. They searched are for macro function definitions. Supports variable substitution for ${workspaceRoot}. For example: "${workspaceRoot}/Macros"._

Bu i tried to use sas.sasautos: in the setting.json, but the option is not reconised.

**Comment by rudvfaden** [comment]
Figured it out. Making putting and example would be helpfull

**Comment by mikmart** [comment]
Thanks. Would you mind expanding on what went wrong in your initial attempt? I'm struggling to see what kind of further example would be helpful. I'd appreciate any ideas.

**Comment by rudvfaden** [comment]
It was unclear to me that the settio had to be in an Array

**Comment by mikmart** [comment]
Thanks. I've added an example to the README and clarified the language in the description.
